package com.atguigu.pojo;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.did
     *
     * @mbggenerated Mon Jun 26 11:10:00 CST 2023
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_name
     *
     * @mbggenerated Mon Jun 26 11:10:00 CST 2023
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.did
     *
     * @return the value of department.did
     *
     * @mbggenerated Mon Jun 26 11:10:00 CST 2023
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.did
     *
     * @param did the value for department.did
     *
     * @mbggenerated Mon Jun 26 11:10:00 CST 2023
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_name
     *
     * @return the value of department.dept_name
     *
     * @mbggenerated Mon Jun 26 11:10:00 CST 2023
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_name
     *
     * @param deptName the value for department.dept_name
     *
     * @mbggenerated Mon Jun 26 11:10:00 CST 2023
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}